name: Manual Deploy to npm 

# This workflow is designed to be triggered manually.
on:
  workflow_dispatch: 
    inputs:
      tagToDeploy:
        description: 'Type name of existing git tag (example: 1.0.3) to push to npm'
        required: true
        type: string 

jobs:
  deploy-npm:
    name: Deploy package to npm 
    environment: release
    runs-on: macos-12
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout provided git tag  
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tagToDeploy }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install npm 11.5.1+ for OIDC support
        run: npm install -g npm@latest

      - name: Test authentication
        run: npm whoami

      - name: Install dependencies
        run: npm ci

      - name: Compile
        run: npm run compile

      - name: Publish to npm
        run: |
          npm version 0.0.0-test-oidc-manual
          npm publish --dry-run --tag test-oidc

